-- ==========================================
-- SCHOOL HUB: PRODUCTION READY SETUP (v2.0)
-- ==========================================
-- Dit script zet de volledige database klaar voor de School Hub.
-- Het combineert alle tabellen, functies, RLS policies en content.
-- WAARSCHUWING: Dit verwijdert alle bestaande data!

-- 0. OPSCHONEN (Clean Slate)
-- ==========================================
drop table if exists inventory cascade;
drop table if exists products cascade;
drop table if exists challenges cascade;
drop table if exists student_progress cascade;
drop table if exists student_answers cascade;
drop table if exists machine_certificates cascade;
drop table if exists machines cascade;
drop table if exists questions cascade;
drop table if exists quizzes cascade;
drop table if exists simulation_results cascade;
drop table if exists tiktok_content_queue cascade;
drop table if exists students cascade;

drop function if exists validate_quiz_answers(uuid, bigint, jsonb);
drop function if exists get_quiz_stats();

-- Extensies (indien nodig)
create extension if not exists "uuid-ossp";

-- 1. TABELLEN AANMAKEN
-- ==========================================

-- Students (Gekoppeld aan Supabase Auth)
create table students (
  id uuid primary key, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text unique,
  name text not null,
  class text not null,
  avatar_url text,
  is_admin boolean default false,
  xp_denken integer default 0,
  xp_veiligheid integer default 0,
  xp_nauwkeurigheid integer default 0,
  xp_metaal integer default 0,
  xp_werkhouding integer default 0,
  xp_teamwork integer default 0,
  xp_creatief integer default 0,
  xp_lassen integer default 0,
  xp_gereedschappen integer default 0,
  xp_machines integer default 0,
  xp_stappenplannen integer default 0,
  total_xp integer generated always as (
    xp_denken + xp_veiligheid + xp_nauwkeurigheid + xp_metaal + 
    xp_werkhouding + xp_teamwork + xp_creatief + xp_lassen + 
    xp_gereedschappen + xp_machines + xp_stappenplannen
  ) stored
);

-- Trigger om automatisch student record aan te maken bij Auth signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.students (id, email, name, class)
  values (
    new.id, 
    new.email, 
    coalesce(new.raw_user_meta_data->>'name', 'Nieuwe Student'),
    coalesce(new.raw_user_meta_data->>'class', 'Klas Onbekend')
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- ZEER BELANGRIJK: Verwijder de oude trigger eerst (indien aanwezig)
do $$
begin
  if exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    drop trigger on_auth_user_created on auth.users;
  end if;
end $$;

-- Maak de trigger aan op de auth.users tabel
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. INHOUD (SEED DATA)
-- ... (rest van de inhoud blijft gelijk) ...

-- 5. AUTOMATISCHE SYNC & UPDATES
-- ==========================================

-- Sync bestaande Auth users (voor als je al geregistreerd was maar de tabel is gereset)
insert into public.students (id, email, name, class)
select id, email, 'Docent/Admin', 'VTI' from auth.users
on conflict (id) do nothing;

-- Maak de eerste gebruiker (waarschijnlijk jij) Admin
update students set is_admin = true where email = 'logic1connections@gmail.com';

-- Einde script
-- ==========================================

-- Quizzes
create table quizzes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  category text,
  level integer default 1,
  passing_score integer default 9,
  question_count integer default 0
);

-- Questions
create table questions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  quiz_id bigint references quizzes(id) on delete cascade not null,
  question text not null,
  options text[] not null,
  correct_index integer not null,
  image_url text
);

-- Student Progress
create table student_progress (
  id bigint generated by default as identity primary key,
  student_id uuid references students(id) on delete cascade not null,
  quiz_id bigint references quizzes(id) on delete cascade not null,
  score integer not null,
  passed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, quiz_id)
);

-- Student Answers (Voor sync van offline antwoorden)
create table student_answers (
  id bigint generated by default as identity primary key,
  student_id uuid references students(id) on delete cascade,
  question_id bigint references questions(id) on delete cascade,
  selected integer not null,
  created_at timestamp with time zone default now()
);

-- Machines Table
create table machines (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  description text,
  image_url text,
  safety_manual_url text,
  quiz_id bigint references quizzes(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Machine Certificates Table
create table machine_certificates (
  id uuid default uuid_generate_v4() primary key,
  student_id uuid references students(id) on delete cascade not null,
  machine_id uuid references machines(id) on delete cascade not null,
  status text check (status in ('certified', 'pending', 'locked')) default 'locked',
  issued_at timestamp with time zone,
  unique(student_id, machine_id)
);

-- Challenges
create table challenges (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  challenger_id uuid references students(id) on delete cascade not null,
  challenged_id uuid references students(id) on delete cascade not null,
  quiz_id bigint references quizzes(id) on delete cascade not null,
  status text default 'pending', 
  challenger_score integer,
  challenged_score integer,
  winner_id uuid references students(id),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Products (Shop)
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price_xp integer not null default 0,
  image_url text,
  type text not null default 'physical',
  content_url text
);

-- Inventory (Purchases)
create table inventory (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id uuid references students(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null
);

-- Simulation Results
create table simulation_results (
  id uuid default gen_random_uuid() primary key,
  student_id uuid references students(id) on delete cascade not null,
  machine_type text not null,
  module_type text not null,
  score integer,
  completed_at timestamp with time zone default now()
);

-- TikTok Content Queue
CREATE TABLE tiktok_content_queue (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    concept TEXT NOT NULL,
    logic_hero TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    video_url TEXT
);

-- 2. FUNCTIES & RPC
-- ==========================================

-- Quiz Validation Function
create or replace function validate_quiz_answers(
    p_student_id uuid,
    p_quiz_id bigint,
    p_answers jsonb
) returns jsonb language plpgsql security definer as $$
declare
    v_total_questions int;
    v_correct_count int := 0;
    v_score int;
    v_passed boolean;
    v_pass_threshold int;
    v_xp_worth int := 10; 
    v_category text;
    v_xp_column text;
begin
    select count(*), max(passing_score), max(category) 
    into v_total_questions, v_pass_threshold, v_category
    from quizzes where id = p_quiz_id;

    select count(*) into v_correct_count
    from (
        select (ans->>'question_id')::bigint as q_id, (ans->>'selected')::int as sel
        from jsonb_array_elements(p_answers) as ans
    ) a
    join questions q on q.id = a.q_id
    where q.correct_index = a.sel;

    v_score := v_correct_count * v_xp_worth;
    v_passed := v_correct_count >= v_pass_threshold;

    insert into student_progress (student_id, quiz_id, score, passed)
    values (p_student_id, p_quiz_id, v_score, v_passed)
    on conflict (student_id, quiz_id) 
    do update set 
        score = case when v_score > student_progress.score then v_score else student_progress.score end,
        passed = v_passed or student_progress.passed;

    v_xp_column := case v_category
        when 'Lassen' then 'xp_lassen'
        when 'Veiligheid' then 'xp_veiligheid'
        when 'Gereedschappen' then 'xp_gereedschappen'
        when 'Machines' then 'xp_machines'
        when 'Stappenplannen' then 'xp_stappenplannen'
        else 'xp_metaal'
    end;

    execute format('update students set %I = %I + %L where id = %L', 
                   v_xp_column, v_xp_column, v_score, p_student_id);

    return jsonb_build_object('score', v_score, 'passed', v_passed);
end;
$$;

-- Analytics Function
create or replace function get_quiz_stats()
returns jsonb language plpgsql security definer as $$
declare
    v_stats jsonb;
begin
    select jsonb_build_object(
        'total_attempts', (select count(*) from student_progress),
        'pass_rate', (
            case when (select count(*) from student_progress) > 0 
            then (select count(*) from student_progress where passed = true) * 100 / (select count(*) from student_progress)
            else 0 end
        ),
        'average_score', (select coalesce(round(avg(score)), 0) from student_progress),
        'difficult_questions', (
            select jsonb_agg(q) from (
                select question, 
                       round(count(case when selected = correct_index then 1 end) * 100.0 / count(*), 1) as success_rate
                from student_answers sa
                join questions q on q.id = sa.question_id
                group by question
                order by success_rate asc
                limit 5
            ) q
        ),
        'popular_categories', (
            select jsonb_agg(c) from (
                select category, count(*) as count
                from quizzes quiz
                join student_progress p on p.quiz_id = quiz.id
                group by category
                order by count desc
                limit 5
            ) c
        )
    ) into v_stats;
    return v_stats;
end;
$$;

-- 3. BEVEILIGING (RLS)
-- ==========================================
alter table students enable row level security;
alter table quizzes enable row level security;
alter table questions enable row level security;
alter table student_progress enable row level security;
alter table student_answers enable row level security;
alter table challenges enable row level security;
alter table products enable row level security;
alter table inventory enable row level security;
alter table simulation_results enable row level security;
alter table machines enable row level security;
alter table machine_certificates enable row level security;
alter table tiktok_content_queue enable row level security;

-- Policies (Controleer auth.uid() voor veiligheid ONLINE)
create policy "Public read quizzes" on quizzes for select using (true);
create policy "Public read questions" on questions for select using (true);
create policy "Public read products" on products for select using (true);
create policy "Public read machines" on machines for select using (true);

create policy "Students view own profile" on students for select using (auth.uid() = id);
create policy "Students update own profile" on students for update using (auth.uid() = id);

create policy "Students view own progress" on student_progress for select using (auth.uid() = student_id);
create policy "Students insert own results" on student_progress for insert with check (auth.uid() = student_id);

create policy "Students view own certificates" on machine_certificates for select using (auth.uid() = student_id);

create policy "Students insert own answers" on student_answers for insert with check (auth.uid() = student_id);

create policy "Challenges access" on challenges for select using (auth.uid() = challenger_id or auth.uid() = challenged_id);
create policy "Challenges insert" on challenges for insert with check (auth.uid() = challenger_id);

create policy "Inventory access" on inventory for select using (auth.uid() = student_id);
create policy "Inventory insert" on inventory for insert with check (auth.uid() = student_id);

create policy "Simulation access" on simulation_results for all using (auth.uid() = student_id);

-- 4. INHOUD (SEED DATA)
-- ==========================================

-- 4.1 Quizzes
insert into quizzes (id, title, description, category, level, question_count, passing_score) values
(10, 'Veiligheid Level 1: Basics', 'Basiskennis PBM en signalisatie.', 'Veiligheid', 1, 5, 4),
(11, 'Veiligheid Level 2: Gevaren', 'Gevaren in de werkplaats.', 'Veiligheid', 2, 5, 4),
(12, 'Veiligheid Level 3: Brand & EHBO', 'Wat te doen bij incidenten?', 'Veiligheid', 3, 5, 4),
(13, 'Veiligheid Level 4: Expert', 'Complexe veiligheidssituaties.', 'Veiligheid', 4, 5, 4),
(20, 'Gereedschappen Level 1: Handgereedschap', 'Hamers, vijlen en zagen.', 'Gereedschappen', 1, 5, 4),
(21, 'Gereedschappen Level 2: Meetgereedschap', 'Schuifmaat en micrometer.', 'Gereedschappen', 2, 5, 4),
(22, 'Gereedschappen Level 3: Elektrisch gereedschap', 'Boormachine en slijpschijf.', 'Gereedschappen', 3, 5, 4),
(23, 'Gereedschappen Level 4: Onderhoud', 'Smeren en scherp houden.', 'Gereedschappen', 4, 5, 4),
(30, 'Machines Level 1: De Kolomboormachine', 'Basisbediening en toerental.', 'Machines', 1, 5, 4),
(31, 'Machines Level 2: De Draaibank', 'Onderdelen en veiligheid.', 'Machines', 2, 5, 4),
(32, 'Machines Level 3: De Freesmachine', 'Opspannen en gereedschap.', 'Machines', 3, 5, 4),
(33, 'Machines Level 4: CNC Intro', 'De basis van computersturing.', 'Machines', 4, 5, 4),
(40, 'Stappenplannen Level 1: Voorbereiding', 'Tekening lezen en aftekenen.', 'Stappenplannen', 1, 5, 4),
(41, 'Stappenplannen Level 2: Bewerken', 'Logische volgorde van handelingen.', 'Stappenplannen', 2, 5, 4),
(42, 'Stappenplannen Level 3: Afwerking', 'Bramen verwijderen en polijsten.', 'Stappenplannen', 3, 5, 4),
(43, 'Stappenplannen Level 4: Controle', 'Kwaliteitscontrole en toleranties.', 'Stappenplannen', 4, 5, 4),
(50, 'Lassen Level 1: Basics', 'Basiskennis lassen en PBM''s.', 'Lassen', 1, 5, 4),
(51, 'Lassen Level 2: Elektrode (BMBE)', 'Basis van het booglassen.', 'Lassen', 2, 5, 4),
(52, 'Lassen Level 3: MIG/MAG & TIG', 'Halfautomaten en precisielassen.', 'Lassen', 3, 5, 4),
(53, 'Lassen Level 4: Lasfouten & Controle', 'Kwaliteit en visuele inspectie.', 'Lassen', 4, 5, 4);

-- 4.2 Questions
insert into questions (quiz_id, question, options, correct_index) values
(10, 'Wat betekent een blauw rond bord met een wit symbool?', ARRAY['Verbod', 'Gebod (verplichting)', 'Waarschuwing', 'Informatie'], 1),
(10, 'Welke PBM is verplicht bij lawaai boven 80dB?', ARRAY['Veiligheidsbril', 'Gehoorbescherming', 'Slijpmasker', 'Laskap'], 1),
(10, 'Wat is de betekenis van een geel driehoekig bord?', ARRAY['Veiligheid', 'Verbod', 'Waarschuwing voor gevaar', 'Eerste hulp'], 2),
(10, 'Wat doe je bij een onveilige situatie?', ARRAY['Negeren', 'Zelf repareren', 'Melden bij de leerkracht', 'Wachten op het einde van de les'], 2),
(10, 'Waarvoor dient een veiligheidsbril?', ARRAY['Tegen fel licht', 'Tegen stof en rondvliegende deeltjes', 'Om beter te zien', 'Tegen warmte'], 1),
(11, 'Welk gevaar vormt een loszittende mouw bij een draaiende machine?', ARRAY['Vervuiling van het werkstuk', 'Grijpgevaar (meesleuren)', 'Verschroeien', 'Geen gevaar'], 1),
(11, 'Wat is een groot risico bij het gebruik van perslucht?', ARRAY['Koude lucht op de huid', 'Inbrengen van lucht in de bloedbaan', 'Lawaai', 'Stofontwikkeling'], 1),
(11, 'Waarom is orde en netheid belangrijk?', ARRAY['Voor de leerkracht', 'Om struikelgevaar te voorkomen', 'Voor meer ruimte', 'Sneller werken'], 1),
(11, 'Welke straling is het gevaarlijkst bij lassen?', ARRAY['Radiogolven', 'Infrarood en UV', 'Microgolven', 'Licht'], 1),
(11, 'Wat is het gevaar van een beschadigde kabel?', ARRAY['Hoger verbruik', 'Elektrocutiegevaar', 'Minder kracht', 'Warmere machine'], 1),
(12, 'Wat doe je bij een brandwonde?', ARRAY['Hulp zoeken', '20 min spoelen met lauw water', 'Zalf smeren', 'Niets'], 1),
(12, 'Blusmiddel bij elektrische brand?', ARRAY['Water', 'CO2 of poeder', 'Schuim', 'Zand'], 1),
(12, 'Eerste actie bij ongeval?', ARRAY['Verplaatsen', 'Waarschuwen leerkracht', 'Direct helpen', 'Foto maken'], 1),
(12, 'Bord groen rechthoek wit kruis?', ARRAY['Gevaar', 'Nooduitgang', 'EHBO', 'Verzamelplaats'], 2),
(12, 'Letten op bij evacuatie?', ARRAY['Spullen pakken', 'Kalm route volgen', 'Lift gebruiken', 'Brand zoeken'], 1),
(13, 'Wat is VCA?', ARRAY['Diploma', 'Veiligheidscertificaat', 'Rijbewijs', 'Merk'], 1),
(13, 'Wanneer CE-markering?', ARRAY['Grote machines', 'Na 1995 EU markt', 'Export', 'Nooit'], 1),
(13, 'Nuleisbewaking functie?', ARRAY['Nul start', 'Geen herstart na stroomuitval', 'Snelheid', 'Verbruik'], 1),
(13, 'Metaalbrand blusklasse?', ARRAY['A', 'D', 'F', 'B'], 1),
(13, 'Wat is LMRA?', ARRAY['Machine', 'Last Minute Risico Analyse', 'Laskap', 'Meter'], 1),
(20, 'Vijl voor ronde opening?', ARRAY['Vlak', 'Half-rond/rond', 'Vierkant', 'Driekant'], 1),
(20, 'Aftekenen op metaal?', ARRAY['Potlood', 'Kraspen', 'Viltstift', 'Balpen'], 1),
(20, 'Functie centerpons?', ARRAY['Gat vullen', 'Beginpunt boor', 'Markeren', 'Doorslaan'], 1),
(20, 'Hamer tegen beschadiging?', ARRAY['Bankhamer', 'Kunststof/rubber', 'Voorhamer', 'Klauwhamer'], 1),
(20, 'Zaag voor metaal?', ARRAY['Handzaag', 'Beugelzaag fijn', 'Kapzaag', 'Schrobzaag'], 1),
(21, 'Nauwkeurigheid schuifmaat?', ARRAY['0,1', '0,05 of 0,02', '1,0', '0,5'], 1),
(21, 'Deel voor dieptematen?', ARRAY['Bekken groot', 'Bekken klein', 'Dieptemaatstang', 'Nonius'], 2),
(21, 'Schaal op loper?', ARRAY['Liniaal', 'Nonius', 'Maatlat', 'Trommel'], 1),
(21, 'Wat is nauwkeuriger?', ARRAY['Schuifmaat', 'Micrometer', 'Gelijk', 'Geen'], 1),
(21, 'Ratel op micrometer?', ARRAY['Lawaai', 'Constante meetdruk', 'Snelheid', 'Vastzetten'], 1),
(22, 'Boormachine met handschoenen?', ARRAY['Ja', 'Nee', 'Kleine boren', 'Staal'], 1),
(22, 'Wisselen slijpschijf?', ARRAY['Kleur', 'Max toerental schijf', 'Prijs', 'Dikte'], 1),
(22, 'Voor instellen elektrisch gereedschap?', ARRAY['Stekker eruit', 'Aanzetten', 'Handschoenen', 'Leerkracht'], 0),
(22, 'Kap boven slijpschijf?', ARRAY['Stof', 'Vonken vangen', 'Koelen', 'Lawaai'], 1),
(22, 'Handen bij haakse slijper?', ARRAY['1', '2', 'Zelf weten', '3'], 1),
(23, 'Vijl reinigen?', ARRAY['Water', 'Vijlenborstel', 'Afkloppen', 'Olie'], 1),
(23, 'Instrumenten reinigen/oliën?', ARRAY['Glanzen', 'Tegen roest/slijtage', 'Hoort zo', 'Kleur'], 1),
(23, 'Slijpsteen controle?', ARRAY['Klanktest', 'Ruiken', 'Proeven', 'Niet'], 0),
(23, 'Boor blauw uitslaat?', ARRAY['Mooier', 'Oververhit/zacht', 'Scherper', 'Niets'], 1),
(23, 'Meetinstrument bij snijgereedschap?', ARRAY['Geur', 'Tegen krassen', 'Plaats', 'Mag'], 1),
(30, 'Boorsleutel na gebruik?', ARRAY['In kop', 'Direct eruit', 'Op machine', 'Ophangen'], 1),
(30, 'Klein werkstuk vastlkemmen?', ARRAY['Hand', 'Machineklem', 'Tang', 'Niet'], 1),
(30, 'Lager toerental bij?', ARRAY['Kleine boor', 'Grote boor', 'Zacht materiaal', 'Haast'], 1),
(30, 'Koelmiddel doel?', ARRAY['Smeren/koelen', 'Schoonmaken', 'Lawaai', 'Stof'], 0),
(30, 'Spanen verwijderen?', ARRAY['Blote handen', 'Borstel/kwast', 'Wegblazen', 'Laten liggen'], 1),
(31, 'Wat draait er bij draaibank?', ARRAY['Beitel', 'Werkstuk', 'Leerkracht', 'Klem'], 1),
(31, 'Onderdeel klemming?', ARRAY['Beitelhouder', 'Klauwplaat', 'Losse kop', 'Bed'], 1),
(31, 'Functie losse kop?', ARRAY['Links houden', 'Ondersteunen/boren', 'Snelheid', 'Aandrijving'], 1),
(31, 'Nooit doen bij draaiende bank?', ARRAY['Kijken', 'Aanraken', 'Koelen', 'Afstand'], 1),
(31, 'Beitel instellen?', ARRAY['Boven center', 'Op center', 'Onder center', 'Maakt niet uit'], 1),
(32, 'Draait bij freesmachine?', ARRAY['Werkstuk', 'Frees', 'Tafel', 'Motoren'], 1),
(32, 'Richtingen tafel?', ARRAY['L/R', 'X, Y, Z', 'O/O', 'Vast'], 1),
(32, 'Meelopend frezen?', ARRAY['Draai=voeding', 'Geen richting', 'Stil', 'Tegen'], 0),
(32, 'Opspanning belangrijk?', ARRAY['Kleur', 'Snijkrachten', 'Lawaai', 'Niet'], 1),
(32, 'Gereedschap voor vlak?', ARRAY['Boor', 'Vlakfrees', 'Ruimer', 'Tap'], 1),
(33, 'CNC afkorting?', ARRAY['Computerized Numerical Control', 'Creative', 'Netwerk', 'Cool'], 0),
(33, 'G-code?', ARRAY['Geheim', 'Beweging/geometrie', 'Naam', 'Fout'], 1),
(33, 'Single block functie?', ARRAY['Hele dag', 'Regel voor regel', 'Sneller', 'Uit'], 1),
(33, 'Nulpunt machine?', ARRAY['Midden wereld', 'Referentie constructeur', 'Operator', 'Anders'], 1),
(33, 'CAD/CAM?', ARRAY['Video', 'Ontwerp/Machine-code', 'Systeem', 'Tekenen'], 1),
(40, 'Eerste stap opdracht?', ARRAY['Zagen', 'Tekening analyse', 'Gereedschap', 'Aanzetten'], 1),
(40, 'Eenheid VTI?', ARRAY['cm', 'mm', 'm', 'dm'], 1),
(40, 'Stippellijn?', ARRAY['Onzichtbaar', 'Hartlijn', 'Breuklijn', 'Maatlijn'], 0),
(40, 'Materiaallijst doel?', ARRAY['Admin', 'Efficiëntie/fouten', 'Leerkracht', 'Tijd'], 1),
(40, 'Na aftekenen?', ARRAY['Boren', 'Controleren', 'Vijlen', 'Vakantie'], 1),
(41, 'Eerst bij gat?', ARRAY['Grote boor', 'Centerpons/voorboren', 'Vijl', 'Slijpen'], 1),
(41, 'Wanneer draaien?', ARRAY['Einde', 'Voor boren', 'Maakt niet uit', 'Tussen slijpen'], 1),
(41, 'Volgorde belangrijk?', ARRAY['Vorm', 'Nauwkeurigheid/tijd', 'Lawaai', 'Niet'], 1),
(41, 'Voor afkorten?', ARRAY['Gebed', 'Overmaat check', 'Vol vermogen', 'Kleur'], 1),
(41, 'Machine kiezen op?', ARRAY['Vrij', 'Tekening bewerking', 'Grootste', 'Leerkracht'], 1),
(42, 'Wat is braam?', ARRAY['Fruit', 'Scherp randje', 'Meetfout', 'Boor'], 1),
(42, 'Braam verwijderen?', ARRAY['Vingers', 'Vijl/ontbramer', 'Hamer', 'Laten'], 1),
(42, 'Waarom ontbramen?', ARRAY['Glans', 'Veiligheid/passing', 'Gewicht', 'Kleur'], 1),
(42, 'Bescherming roest?', ARRAY['Water', 'Invetten/oliën/verven', 'Buiten', 'Niets'], 1),
(42, 'Polijsten?', ARRAY['Kapot', 'Glad/glanzend', 'Gaten boren', 'Smerig'], 1),
(43, 'Tolerantie?', ARRAY['Mag alles', 'Toegestane afwijking', 'Hardheid', 'Prijs'], 1),
(43, 'Kwaliteitscontrole?', ARRAY['Naar huis', 'Check eisen tekening', 'Machine check', 'Bedank'], 1),
(43, 'Check haakse hoek?', ARRAY['Schuifmaat', 'Blokhaak', 'Liniaal', 'Passer'], 1),
(43, 'Maat buiten tolerantie?', ARRAY['Verbergen', 'Melden/herstel check', 'Inleveren', 'Weggooien'], 1),
(43, 'Eindcontrole?', ARRAY['Punten', 'Functionaliteit', 'Tijd doden', 'Overslaan'], 1),
(50, 'Tegen lasogen?', ARRAY['Veiligheidsbril', 'Laskap filter', 'Zonnebril', 'Stofmasker'], 1),
(50, 'Lassen gegalvaniseerd?', ARRAY['Plakt niet', 'Zinkdampen', 'Warm', 'Geen'], 1),
(50, 'Zuurstoffles kleur?', ARRAY['Rood', 'Blauw', 'Grijs', 'Groen'], 1),
(50, 'Lederen handschoenen?', ARRAY['Kou', 'Hitte/vonken/UV', 'Grip', 'Verplicht'], 1),
(50, 'Klaar met lassen?', ARRAY['Weggaan', 'Uit/afkoelen', 'Ventilatie uit', 'Kast'], 1),
(51, 'BMBE afkorting?', ARRAY['Booglassen Met Beklede Elektrode', 'Buiten', 'Basis', 'Beter'], 0),
(51, 'Bekleding doel?', ARRAY['Kleur', 'Beschermgas/slak', 'Isolatie', 'Sterkte'], 1),
(51, 'Beschermlaag op las?', ARRAY['Roest', 'Slak', 'Verf', 'Vet'], 1),
(51, 'Booglengte te groot?', ARRAY['Mooier', 'Spatten/onstabiel', 'Kapot', 'Lawaai'], 1),
(51, 'Beweging elektrode?', ARRAY['Heen/weer', 'Zwaai/recht', 'Cirkels', 'Stippen'], 1),
(52, 'MIG vs MAG?', ARRAY['Machine', 'Inert vs Actief gas', 'Snelheid', 'Prijs'], 1),
(52, 'TIG afkorting?', ARRAY['Tungsten Inert Gas', 'Garage', 'Goed', 'Gelijk'], 0),
(52, 'Beschermgas TIG?', ARRAY['CO2', 'Argon', 'Zuurstof', 'Lachgas'], 1),
(52, 'Voordeel MIG/MAG?', ARRAY['Goedkoop', 'Continu lassen', 'Minder materiaal', 'Geen stroom'], 1),
(52, 'Wolfraam afsmeltend?', ARRAY['Ja', 'Nee', 'Alu', 'Soms'], 1),
(53, 'Randinkerving?', ARRAY['Inkeping door stroom', 'Beitel', 'Meetfout', 'Naad'], 0),
(53, 'Porositeit oorzaak?', ARRAY['Te veel stroom', 'Te weinig of geen beschermgas', 'Te dikke plaat', 'Te koud water'], 1),
(53, 'Bindfout?', ARRAY['Geen samensmelting', 'Niet verbonden', 'Vast', 'Stappenplan'], 0),
(53, 'Visuele controle?', ARRAY['Hamer', 'Oog/lasnaadmeter', 'Röntgen', 'Proeven'], 1),
(53, 'Slakinsluiting probleem?', ARRAY['Ziet niet uit', 'Verzwakt las', 'Zwaar', 'Geen'], 1);

-- 4.3 Machines
insert into machines (id, name, description, image_url, safety_manual_url, quiz_id) values 
('00000000-0000-0000-0000-000000000010', 'Kolomboormachine', 'Voor het boren van gaten in metaal.', 'assets/machines/boormachine.jpg', 'assets/manuals/boormachine.pdf', 30),
('00000000-0000-0000-0000-000000000011', 'Draaibank', 'Voor het draaien van ronde werkstukken.', 'assets/machines/draaibank.jpg', 'assets/manuals/draaibank.pdf', 31),
('00000000-0000-0000-0000-000000000012', 'Freesmachine', 'Voor het bewerken van vlakke oppervlakken.', 'assets/machines/freesmachine.jpg', 'assets/manuals/freesmachine.pdf', 32),
('00000000-0000-0000-0000-000000000013', 'Slijpmachine', 'Voor het afbramen en slijpen van beitels.', 'assets/machines/slijpmachine.jpg', 'assets/manuals/slijpmachine.pdf', 23);

-- 4.4 Shop Products
insert into products (id, title, description, price_xp, type, image_url) values
(1, 'Suske en Wiske', 'Strip naar keuze.', 500, 'physical', 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Suske_en_Wiske_logo.svg/1200px-Suske_en_Wiske_logo.svg.png'),
(2, 'Jommeke Bundel', '3 strips.', 1200, 'physical', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Jommeke_statue_Middelkerke.jpg/800px-Jommeke_statue_Middelkerke.jpg'),
(3, 'Mega Strip Pakket', '10 strips naar keuze.', 4500, 'physical', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Comic_Books.jpg/1200px-Comic_Books.jpg');

-- 4.5 TikTok Queue Seeds
INSERT INTO tiktok_content_queue (concept, logic_hero) VALUES
('Verkeerde tang gebruiken bij het strippen van kabels', 'Navid'),
('Metalen boor gebruiken voor hout op hoge snelheid', 'Juan'),
('Zwarte draad als aarding gebruiken (gevaarlijk!)', 'Matteo');
