-- Create Quizzes Table
create table quizzes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  category text,
  question_count integer default 0
);

-- Create Questions Table
create table questions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  quiz_id bigint references quizzes(id) on delete cascade not null,
  question text not null,
  options text[] not null, -- Array of strings
  correct_index integer not null -- 0-based index
);

-- Insert Sample Data (Quizzes)
insert into quizzes (title, description, category, question_count) values
('Wiskunde: Hoofdrekenen', 'Test je snelheid met optellen en aftrekken tot 100.', 'Wiskunde', 3),
('Geschiedenis: De Romeinen', 'Hoeveel weet jij over het Romeinse Rijk?', 'Geschiedenis', 3),
('Aardrijkskunde: Hoofdsteden', 'Ken jij de hoofdsteden van Europa?', 'Aardrijkskunde', 3);

-- Insert Sample Data (Questions for Math Quiz - ID 1)
insert into questions (quiz_id, question, options, correct_index) values
(1, 'Wat is 15 + 27?', ARRAY['32', '42', '52', '45'], 1),
(1, 'Wat is 100 - 35?', ARRAY['55', '65', '75', '60'], 1),
(1, 'Wat is 8 x 7?', ARRAY['54', '56', '58', '62'], 1);

-- Insert Sample Data (Questions for History Quiz - ID 2)
insert into questions (quiz_id, question, options, correct_index) values
(2, 'Wie was de eerste keizer van Rome?', ARRAY['Julius Caesar', 'Augustus', 'Nero', 'Trajanus'], 1),
(2, 'In welk jaar viel het West-Romeinse Rijk?', ARRAY['476 n.Chr.', '1453 n.Chr.', '33 n.Chr.', '800 n.Chr.'], 0),
(2, 'Welke taal spraken de Romeinen?', ARRAY['Italiaans', 'Grieks', 'Latijn', 'Frans'], 2);

-- Insert Sample Data (Questions for Geography Quiz - ID 3)
insert into questions (quiz_id, question, options, correct_index) values
(3, 'Wat is de hoofdstad van Duitsland?', ARRAY['München', 'Hamburg', 'Berlijn', 'Frankfurt'], 2),
(3, 'Wat is de hoofdstad van Spanje?', ARRAY['Barcelona', 'Madrid', 'Sevilla', 'Valencia'], 1),
(3, 'Wat is de hoofdstad van Italië?', ARRAY['Milaan', 'Venetië', 'Napels', 'Rome'], 3);

-- Enable Row Level Security (RLS) but allow public read access for now
alter table quizzes enable row level security;
alter table questions enable row level security;

create policy "Public quizzes are viewable by everyone"
  on quizzes for select
  to anon
  using (true);

create policy "Public questions are viewable by everyone"
  on questions for select
  to anon
  using (true);
