-- Drop table if exists to allow clean retry
drop table if exists students;

-- Create Students Table
create table students (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  class text not null,
  avatar_url text,
  xp_denken integer default 0,
  xp_veiligheid integer default 0,
  xp_nauwkeurigheid integer default 0,
  xp_metaal integer default 0,
  xp_werkhouding integer default 0,
  xp_teamwork integer default 0,
  xp_creatief integer default 0,
  total_xp integer generated always as (xp_denken + xp_veiligheid + xp_nauwkeurigheid + xp_metaal + xp_werkhouding + xp_teamwork + xp_creatief) stored
);

-- Enable RLS
alter table students enable row level security;

-- Allow public access (for simplicity in this phase)
create policy "Public students are viewable by everyone"
  on students for select
  to anon
  using (true);

create policy "Public students are editable by everyone"
  on students for update
  to anon
  using (true);

create policy "Public students are insertable by everyone"
  on students for insert
  to anon
  with check (true);

-- Insert Data (3ME)
insert into students (name, class) values
('Wael Aklofee', '3ME'),
('Khaled Alghoul', '3ME'),
('Ayman Bajrami', '3ME'),
('Imal Betanai', '3ME'),
('Johnson Michael', '3ME'),
('Navid Jabarkhel', '3ME'),
('Saqib Jabar Khil', '3ME'),
('Lord Martin', '3ME'),
('Dior Miftari', '3ME'),
('Sadat Mosawer', '3ME'),
('Mohammed Anwar', '3ME');

-- Insert Data (4ME)
insert into students (name, class) values
('Abdelwasa Muni', '4ME'),
('Amin Shervan', '4ME'),
('Cheikh Sidi Bou', '4ME'),
('Cuenen Jordy', '4ME'),
('Dzelili Fisnik', '4ME'),
('Florens Djiani', '4ME'),
('Kamwa Kamden', '4ME'),
('Mendy Noah', '4ME'),
('Tsegay Yuiel', '4ME');

-- Insert Data (OV4)
insert into students (name, class, xp_veiligheid) values
('Juan', 'OV4', 36); -- Juan has 36 XP in Veiligheid (Total XP is auto-calculated)

insert into students (name, class) values
('Mathis', 'OV4'),
('Sam', 'OV4'),
('Milan', 'OV4'),
('Matteo', 'OV4');
