-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price_xp integer not null default 0,
  image_url text, -- URL to cover image
  type text not null default 'physical', -- 'physical' or 'digital'
  content_url text -- Link to PDF if digital
);

-- Create Inventory Table (Purchases)
create table inventory (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id bigint references students(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null
);

-- Enable RLS
alter table products enable row level security;
alter table inventory enable row level security;

-- Public Access Policies (Simplified)
create policy "Public products are viewable by everyone" on products for select to anon using (true);
create policy "Public inventory is viewable by everyone" on inventory for select to anon using (true);
create policy "Public inventory is insertable by everyone" on inventory for insert to anon with check (true);

-- Insert Sample Products
insert into products (title, description, price_xp, type, image_url) values
('Suske en Wiske: De Apenkermis', 'Een klassiek avontuur vol humor en spanning.', 500, 'physical', 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Suske_en_Wiske_logo.svg/1200px-Suske_en_Wiske_logo.svg.png'),
('Jommeke Bundel (3 stuks)', 'Drie spannende verhalen van Jommeke in één pakket.', 1200, 'physical', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Jommeke_statue_Middelkerke.jpg/800px-Jommeke_statue_Middelkerke.jpg'),
('Kiekeboe: De Hoed van Geeraard', 'Fanny en de rest in een mysterieus avontuur.', 600, 'physical', 'https://upload.wikimedia.org/wikipedia/en/9/9a/Kiekeboe_logo.png'),
('Mega Strip Pakket (10 stuks)', 'Voor de echte lezer! Een mix van alles.', 5000, 'physical', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Comic_Books.jpg/1200px-Comic_Books.jpg');
