-- Add xp_spent column to students
alter table students add column if not exists xp_spent integer default 0;

-- Ensure products and inventory tables exist (in case they weren't created yet)
create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price_xp integer not null default 0,
  image_url text,
  type text not null default 'physical',
  content_url text
);

create table if not exists inventory (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id bigint references students(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null
);

-- Enable RLS
alter table products enable row level security;
alter table inventory enable row level security;

-- Policies
create policy "Public products are viewable by everyone" on products for select to anon using (true);
create policy "Public inventory is viewable by everyone" on inventory for select to anon using (true);
create policy "Public inventory is insertable by everyone" on inventory for insert to anon with check (true);

-- Insert Sample Products (if empty)
insert into products (title, description, price_xp, type, image_url) 
select 'Suske en Wiske: De Apenkermis', 'Een klassiek avontuur vol humor en spanning.', 500, 'physical', 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Suske_en_Wiske_logo.svg/1200px-Suske_en_Wiske_logo.svg.png'
where not exists (select 1 from products where title = 'Suske en Wiske: De Apenkermis');

insert into products (title, description, price_xp, type, image_url)
select 'Jommeke Bundel (3 stuks)', 'Drie spannende verhalen van Jommeke in één pakket.', 1200, 'physical', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Jommeke_statue_Middelkerke.jpg/800px-Jommeke_statue_Middelkerke.jpg'
where not exists (select 1 from products where title = 'Jommeke Bundel (3 stuks)');

insert into products (title, description, price_xp, type, image_url)
select 'Kiekeboe: De Hoed van Geeraard', 'Fanny en de rest in een mysterieus avontuur.', 600, 'physical', 'https://upload.wikimedia.org/wikipedia/en/9/9a/Kiekeboe_logo.png'
where not exists (select 1 from products where title = 'Kiekeboe: De Hoed van Geeraard');

insert into products (title, description, price_xp, type, image_url)
select 'Mega Strip Pakket (10 stuks)', 'Voor de echte lezer! Een mix van alles.', 5000, 'physical', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Comic_Books.jpg/1200px-Comic_Books.jpg'
where not exists (select 1 from products where title = 'Mega Strip Pakket (10 stuks)');
