-- Add level and passing score to quizzes
alter table quizzes add column level integer default 1;
alter table quizzes add column passing_score integer default 9;

-- Add admin flag to students
alter table students add column is_admin boolean default false;

-- Create Student Progress Table
create table if not exists student_progress (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade not null,
  quiz_id bigint references quizzes(id) on delete cascade not null,
  score integer not null,
  passed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, quiz_id)
);

-- Create Challenges Table
create table if not exists challenges (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  challenger_id bigint references students(id) on delete cascade not null,
  challenged_id bigint references students(id) on delete cascade not null,
  quiz_id bigint references quizzes(id) on delete cascade not null,
  status text default 'pending', -- pending, accepted, completed, declined
  challenger_score integer,
  challenged_score integer,
  winner_id bigint references students(id),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS Policies for Progress
alter table student_progress enable row level security;
create policy "Users can see their own progress" on student_progress for select using (true); -- Public for now as per user pattern
create policy "Users can insert their own progress" on student_progress for insert with check (true);

-- RLS Policies for Challenges
alter table challenges enable row level security;
create policy "Public challenges access" on challenges for select using (true);
create policy "Public challenges insert" on challenges for insert with check (true);
create policy "Public challenges update" on challenges for update using (true);

-- Set Birger as Admin (Manual update would be needed, but let's provide the query)
-- update students set is_admin = true where name = 'Birger'; 
